sudo: required
dist: trusty
language: node_js

node_js:
    - "8.10.0"

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - "npm run lint"
    - "npm run unit"
    - "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverages"


